# Makefile for the focaltech touchscreen drivers.

obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_3683G) += focaltech_3683g.o

focaltech_3683g-y := \
	focaltech_core.o \
	focaltech_ex_fun.o \
	focaltech_ex_mode.o \
	focaltech_gesture.o \
	focaltech_esdcheck.o \
	focaltech_point_report_check.o \
	focaltech_spi_v2.o \
	focaltech_debug.o \
	focaltech_flash.o \
	focaltech_flash/focaltech_upgrade_ft3681.o \
	focaltech_flash/focaltech_upgrade_ft3683g.o
